### ISSUE TITLE
Integrate webpack-dashboard

### ISSUE THREAD

**Issue by eliperelman** [mozilla/neo#44]
Formidable just came out with this awesome tool:

https://github.com/FormidableLabs/webpack-dashboard

I think we should integrate this as the default `npm start` view.

**Comment by eliperelman** [comment]
I think this is something we just turn on for the development configuration.

**Comment by reznord** [comment]
Accepted, webpack-dashboard is just simply awesome, I am using it for my project. 

It reduces a lot of headache for developers, especially when they are using hot reloading with hmr.
