### ISSUE TITLE
Support compiling with Node.js versions before v6

### ISSUE THREAD

**Issue by eliperelman** [mozilla/neo#45]
Right now we use destructuring in Neo code, which can't run natively prior to v6. I think with a few changes we could support earlier versions.

**Comment by alanmoo** [comment]
I wonder what the likelihood of someone bringing this in to an older Node project is compared to starting a new project with it (or using an old version of Node to start a new project). Is it actually a useful thing to support?

**Comment by eliperelman** [comment]
It's not that hard to support it from a refactoring standpoint, so in terms value, I'm not really sure. I guess it does depend on if people actually use older versions for creating new apps. I'll open a PR and see if there are any reservations about it.

**Comment by eliperelman** [comment]
Fixed by #46.
