### ISSUE TITLE
Dockerize no route to host

### ISSUE THREAD

**Issue by tdhz77** [mozilla/neo#52]
Trying to figure out how to set the ip in configuration?
I believe it might be set to localhost and probably needs to be set at 0.0.0.0 

This is my first docker image though, so I could be mistaken.

**Comment by eliperelman** [comment]
Looking at the current `start` command:

https://github.com/mozilla/neo/blob/master/commands/start/index.js#L15

It is pulling out the `devServer.host` value, or using `localhost` as the host. You can override this by overriding that value in your own config. For example, create a `dev.config.js` file in the root of your project, and put something in like this:

```js
const config = require('mozilla-neo/config/webpack.dev');

config.devServer.host = '0.0.0.0';

module.exports = config;
```

Then pass this config to Neo in your `package.json`:

```js
"scripts": {
  "start": "neo start --config dev.config.js"
}
```

And that should set the host when starting. If that doesn't work correctly, please re-open and post some more details. Thanks!
