### ISSUE TITLE
Disable devtools

### ISSUE THREAD

**Issue by Industrial** [mozilla/neo#53]
Hi!

I'd like to use the Redux Devtools by using the browser plugin. Is it possible to turn the bundled devtools off?

Also, the browser plugin version gives me the error: `No store found. Make sure to follow the instructions.`

**Comment by eliperelman** [comment]
@Industrial Right now the redux-devtools are configured in the app.js in the `src` of the project. If you remove the `DevTools` component in there, it should be removed, and you can use the browser plugin.

As far as the browser plugin error is concerned, I'm unfortunately not familiar with that, so if it still gives you problems after removing the dev tools from app.js, you may want to refer to its docs and possibly file a bug there. Let me know if you have any troubles removing the dev tools from app.js.

Thanks!

**Comment by Industrial** [comment]
Right, thanks a lot :-)
