### ISSUE TITLE
Serving assets with the dev server

### ISSUE THREAD

**Issue by pierre-b** [mozilla/neo#54]
Hi guys, @eliperelman,

The dev server can't serve static assets (images...), I tried to put them at the root level and /src but it's not working.

That would be nice to have a /public or /assets folder in the default config configured to serve a root URL like /my-logo.png

Thanks ;)

**Comment by eliperelman** [comment]
I think this would be good to have. I added the first bug label in case someone gets around to it before I do. In the mean time, you should be able to place assets in your `src` directory and import them ala:

```jsx
import imageUrl from './image.png';

<img src={imageUrl} />
```

**Comment by pierre-b** [comment]
Thanks @eliperelman for the workaround!

**Comment by pierre-b** [comment]
My bad, the dev server is serving assets from /src.

However it would be nice to have a /src/assets by default with the "publicPath: assets" (https://webpack.github.io/docs/webpack-dev-server.html#content-base).

This ways we can put all the fonts/images/favicons in the /src/assets, and the template.ejs would have to serve /assets/bundle.js...

Feel free to close this issue though!

**Comment by gasolin** [comment]
I wonder if `static` is a more convention name than `assets` to host static files :/

**Comment by eliperelman** [comment]
@gasolin I'm happy to accept a PR with either path name.
