### ISSUE TITLE
json-loader error

### ISSUE THREAD

**Issue by pierre-b** [mozilla/neo#55]
Hi @eliperelman , when importing moment-timezone into my project I get the following error:

```
ERROR in ./~/moment-timezone/data/packed/latest.json
Module parse failed: /my-project/node_modules/moment-timezone/data/packed/latest.json Unexpected token (2:10)
You may need an appropriate loader to handle this file type.
```

After playing around with the json loader in the webpack I still can't get rid of it, do you know how to solve this please?

Thanks!

**Comment by pierre-b** [comment]
Found out the webpack core config prevents the webpack "json-loader" to parse the "node_modules" and "bower_components"  folders.

For others who might encounter a similar error, here is how to deal with it with a ```dev.config.js```config file:
```js
const dev = require('mozilla-neo/config/webpack.dev');
const { join } = require('path');
const ContextReplacementPlugin = require('webpack').ContextReplacementPlugin;

// http://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack
// dev.plugins.push(new IgnorePlugin(/^\.\/locale$/, /moment$/));
dev.plugins.push(new ContextReplacementPlugin(/moment[\/\\]locale$/, /en/));


dev.module.loaders[2].include.push(join(process.cwd(), '/node_modules/moment-timezone'));
dev.module.loaders[2].exclude = /((node_modules\/(?!moment-timezone))|bower_components)/;

module.exports = dev;
```

**Comment by pierre-b** [comment]
I guess the ```node_modules```folders are excluded in the parsers to boost the build process, however it looks like a hack to tune it with a ```dev.config.js```file.

@eliperelman  don't you think it would be nice to control the excluded folders into the config in package.json?

**Comment by eliperelman** [comment]
@pierre-b could you confirm if this is still an issue with 2.4.0?

**Comment by pierre-b** [comment]
The 2.4.0 seems not published here, but reading https://github.com/mozilla/neo/pull/56/commits/2f9edb6077a2d7d692f3fe278c710dfdc58bd674 will fix the issue.
Is there any performance downside to not exclude ```node_modules``` from the parsers?

**Comment by pierre-b** [comment]
@eliperelman the json parsing is no more an issue with 2.4.0

**Comment by eliperelman** [comment]
I think this is resolved, please re-open if still an issue.
