### ISSUE TITLE
FlowStatusPlugin doesn't print flow status checks

### ISSUE THREAD

**Issue by robert-zaremba** [mozilla/neo#64]
I was following the flow setup described in the [Create and build React web applications with zero initial configuration and minimal fuss](https://blog.eliperelman.com/neo-8bf3d7325f7#.5zmcm8x2h) post:
- installing flow-status-webpack-plugin
- running `node_modules/.bin/flow init`
- updating `.flowconfig` file
- updating `package.json` to add `--config dev.config.js` argument to `neo start`
- creating `dev.config.js`:

```
const dev = require('mozilla-neo/config/webpack.dev');
const FlowStatusPlugin = require('flow-status-webpack-plugin/index');

dev.plugins.push(new FlowStatusPlugin({binaryPath: 'node_modules/.bin/flow'}));

module.exports = dev
```

I've added a sample function which breaks type, to one of the sources:

```
function display(x: string): string {
    return x.length;
}
```

When running `npm start` I don't see flow status after modifying any file, though my editor displays nice notification that  return type is incompatybile.

Is there something wrong with my setup or `FlowStatusPlugin` doesn't display status?

**Comment by robert-zaremba** [comment]
ad the same time I don't see lint issues reported while running `npm start`. Did I miss something in the configuration?

**Comment by eliperelman** [comment]
Do you have any details around your node/npm/yarn version, and OS?

**Comment by robert-zaremba** [comment]
@eliperelman thanks for looking at this.
node: v6.6.0
npm: 3.10.3
OS: openSUSE 42.1 (x86_64)

**Comment by eliperelman** [comment]
I can replicate, and it looks like the issue is in the flow-status-webpack-plugin:

https://github.com/diegodurli/flow-status-webpack-plugin/issues/17

So your options are to either install `flow-status-webpack-plugin@0.1.5`, or manually configure the plugin to write the pass/fail messages to stdout:

https://github.com/diegodurli/flow-status-webpack-plugin/issues/17#issuecomment-253777411

**Comment by robert-zaremba** [comment]
Thanks for looking at it.
Indeed. There is a problem with latest versions:
* 0.1.5 works fine
* 0.1.6 and 0.1.7 don't work

**Comment by robert-zaremba** [comment]
Just for documentation: the best solution is to create `FlowStatusPlugin` as explained in https://github.com/diegodurli/flow-status-webpack-plugin/issues/17#issuecomment-253777411

**Comment by eliperelman** [comment]
You could shorten it even more:

```js
new FlowStatusWebpackPlugin({
  binaryPath: 'node_modules/.bin/flow',
  onSuccess: console.log,
  onError: console.error
})
```
