### ISSUE TITLE
Switch Neo to be a neutrino preset, or deprecate in favor of neutrino-preset-react

### ISSUE THREAD

**Issue by eliperelman** [mozilla/neo#68]
When I created Neo, it was meant highly React-Redux-boilerplate specific. I have since been working on development of [neutrino](https://github.com/mozilla-neutrino/neutrino), which splits Neo out into two pieces: a wrapped Webpack build system, and a way to have pre-configured presets.

Right now Neo is all-in-one; installing it comes with the build system and all the configuration needed to build. Neutrino is slightly different; you use 2 development dependencies: neutrino and a build preset. For example, if I wanted to build a baseline React project, I could install `neutrino` and `neutrino-preset-react`.

Neo does more than just a baseline React project by including Sass building, but anything more than that either comes from scaffolding, or project-specific includes.

Both tools support project-based configuration overrides, but neutrino makes management of these simpler by easily installing from npm a pre-configured preset.

Leaving this open to discuss possibilities.

**Comment by gasolin** [comment]
I like that approach, maybe it worth to add a note on neo's README to indicate the stat
